services:
  backend:
    image: alexzengg/quirknotes_backend:latest
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  frontend:
    image: alexzengg/quirknotes_frontend:latest
    ports:
      - "3000:80"

  mongodb:
    image: mongo:latest
    ports:
    - "27017:27017"
